name: Fuzz ProjectX2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  build_and_fuzz:
    runs-on: ubuntu-latest

    steps:
      # Checkout latest code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Docker in the environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker container for ProjectX
      - name: Build Docker image for ProjectX
        run: docker build -t projectx2-fuzzer -f ProjectX2-main/Dockerfile ProjectX2-main

      # Run fuzzer inside the Docker container
      - name: Run fuzzer
        run: docker run projectx2-fuzzer